Repository ivao-xa/sectorfiles, pull requests merged in 2021-06, with the labels that each got.

#4 Fixed table formatting in README.
  README.md
Labels: bug, documentation

#6 Fixed MagVar in Anchorage Center.
  PAZA Anchorage ARTCC.isc
Labels: USA, bug, documentation, navigation

#7 Updated airways, airports, fixes, runways, KJFK & KEWR SIDs & STARs
  Include/XA/kzny/airac/airports.ap
  Include/XA/kzny/airac/awhigh.awh
  Include/XA/kzny/airac/awlow.awl
  Include/XA/kzny/airac/fixes.fix
  Include/XA/kzny/airac/runways.rw
  Include/XA/kzny/kewr.sid
  Include/XA/kzny/kjfk.sid
  Include/XA/kzny/kjfk.str
Labels: USA, navigation

#8 Added entire missing TJZS sectorfile to repository
  Include/XA/tjzs/GEO/coastline.geo
  Include/XA/tjzs/airac/airports.ap
  Include/XA/tjzs/airac/awhigh.awh
  Include/XA/tjzs/airac/awlow.awl
  Include/XA/tjzs/airac/fixes.fix
  Include/XA/tjzs/airac/ndb.ndb
  Include/XA/tjzs/airac/runways.rw
  Include/XA/tjzs/airac/vor.vor
  Include/XA/tjzs/airspace/app.artcc
  Include/XA/tjzs/airspace/class_c.artcc
  Include/XA/tjzs/airspace/class_d.artcc
  Include/XA/tjzs/airspace/class_e.artcc
  Include/XA/tjzs/airspace/tjzs_aor.fcl
  Include/XA/tjzs/airspace/tzjs.artcc
  Include/XA/tjzs/app/tjsj_app.geo
  Include/XA/tjzs/atc.atc
  Include/XA/tjzs/tist.tfl
  Include/XA/tjzs/tisx.tfl
  Include/XA/tjzs/tjbq.tfl
  Include/XA/tjzs/tjig.tfl
  Include/XA/tjzs/tjsj.gts
  Include/XA/tjzs/tjsj.sid
  Include/XA/tjzs/tjsj.str
  Include/XA/tjzs/tjsj.tfl
  Include/XA/tjzs/tjsj.txi
  Include/XA/tjzs/tncm.gts
  Include/XA/tjzs/tncm.sid
  Include/XA/tjzs/tncm.str
  Include/XA/tjzs/tncm.tfl
  Include/XA/tjzs/tncm.txi
  Include/XA/tjzs/tzjs_ctr.tfl
  Include/XA/tjzs/tzjs_s_ctr.tfl
  TJZS San Juan ARTCC.isc
Labels: USA, documentation, enhancement, graphics, navigation

#9 Added Auto-ZIP Action
  .github/workflows/ZIP.yaml
Labels: enhancement

#12 Added Hamilton Intl. CYHM Airport Taxiways, Runways and Buildings.
  .gitignore
  CZYZ Toronto FIR.isc
  Include/XA/czyz/cyhm.tfl
  Include/XA/czyz/cyhm.txi
  Include/XA/czyz/cyhm_txicenterlines.geo
Labels: Canada, enhancement, graphics

#13 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/update-request.md
Labels: documentation

#10 Fixed bug in KZFW & KZAK ZIP action
  .github/workflows/ZIP.yaml
  .github/workflows/ZIP.yml
Labels: bug

#15 updated txi files, added missing tracon map files, updated isc file, …
  Include/XA/kzma/06fa.txi
  Include/XA/kzma/airac/airports.ap
  Include/XA/kzma/airspace/kzma_high.artcc
  Include/XA/kzma/app/_faa_videomaps.zip
  Include/XA/kzma/app/ftmyers_tracon_east.geo
  Include/XA/kzma/app/ftmyers_tracon_west.geo
  Include/XA/kzma/app/homestead_approach.geo
  Include/XA/kzma/app/mbpv.artcc
  Include/XA/kzma/app/miami_tracon_east.geo
  Include/XA/kzma/app/miami_tracon_west.geo
  Include/XA/kzma/app/navykeywest_tracon.geo
  Include/XA/kzma/app/orlando_tracon.geo
  Include/XA/kzma/app/palmbeach_tracon_east.geo
  Include/XA/kzma/app/palmbeach_tracon_west.geo
  Include/XA/kzma/app/tampa_tracon_north.geo
  Include/XA/kzma/app/tampa_tracon_south.geo
  Include/XA/kzma/kapf.txi
  Include/XA/kzma/kbct.txi
  Include/XA/kzma/kbow.txi
  Include/XA/kzma/kcof.txi
  Include/XA/kzma/keyw.txi
  Include/XA/kzma/kfll.sid
  Include/XA/kzma/kfll.str
  Include/XA/kzma/kfll.txi
  Include/XA/kzma/kfmy.txi
  Include/XA/kzma/kfpr.txi
  Include/XA/kzma/kfxe.txi
  Include/XA/kzma/khst.txi
  Include/XA/kzma/khwo.txi
  Include/XA/kzma/kism.txi
  Include/XA/kzma/klal.txi
  Include/XA/kzma/kmcf.txi
  Include/XA/kzma/kmco.str
  Include/XA/kzma/kmco.txi
  Include/XA/kzma/kmia.str
  Include/XA/kzma/kmia.txi
  Include/XA/kzma/kmlb.txi
  Include/XA/kzma/knqx.txi
  Include/XA/kzma/kopf.txi
  Include/XA/kzma/kpbi.str
  Include/XA/kzma/kpbi.txi
  Include/XA/kzma/kpgd.txi
  Include/XA/kzma/kpie.txi
  Include/XA/kzma/kpmp.txi
  Include/XA/kzma/krsw.txi
  Include/XA/kzma/kspg.txi
  Include/XA/kzma/ksrq.txi
  Include/XA/kzma/ksua.txi
  Include/XA/kzma/ktix.txi
  Include/XA/kzma/ktmb.txi
  Include/XA/kzma/ktpa.str
  Include/XA/kzma/ktpa.txi
  Include/XA/kzma/kvrb.txi
  KZMA Miami ARTCC.isc
Labels: USA, navigation

#16 ZMA MYNN(assau) necessary update
  Include/XA/kzma/airac/fixes.fix
  Include/XA/kzma/mynn.sid
  Include/XA/kzma/mynn.str
  Include/XA/kzma/mynn.txi
Labels: Bahamas, navigation

#17 Removed extra (incorrect) ZIP action
  .github/workflows/ZIP.yml
Labels: bug, documentation

#19 Modified KZDV and ZAK entries
  .github/workflows/ZIP.yaml
Labels: documentation

#25 Added airport CYXT to Vancouver Sector
  Include/XA/czvr/cyxt.tfl
Labels: Canada, enhancement, graphics

#30 Created Catalina KAVX graphics.
  Include/XA/kzla/kavx.tfl
Labels: USA, enhancement, graphics

#26 Corrected ARTCC title, removed buildings at KAFF
  Include/XA/kzdv/kaff.tfl
  KZDV Denver 2014.isc
  KZDV Denver ARTCC.isc
Labels: USA, documentation, graphics

#31 KZNY: Update isc file, cleaned up kjfk star file
  Include/XA/kzny/kjfk.str
  KZNY New York ARTCC.isc
Labels: USA, documentation

#32 Added Tofino and Kamloops Airports graphics.
  Include/XA/czvr/cyaz.tfl
  Include/XA/czvr/cyka.tfl
Labels: Canada, enhancement, graphics

#36 Updated Class C CYVR Airspace.
  Include/XA/czvr/airspace/class c.artcc
Labels: Canada, documentation, navigation

#41 Updated KZLA procedures from Navigraph data.
  Include/XA/kzla/kbur.sid
  Include/XA/kzla/kbur.str
  Include/XA/kzla/klas.sid
  Include/XA/kzla/klas.str
  Include/XA/kzla/klax.sid
  Include/XA/kzla/klax.str
  Include/XA/kzla/kont.sid
  Include/XA/kzla/kont.str
  Include/XA/kzla/ksan.sid
  Include/XA/kzla/ksan.str
  Include/XA/kzla/ksna.sid
  Include/XA/kzla/ksna.str
Labels: USA, enhancement, navigation

#40 Kzkc graphics 190881
  Include/XA/kzkc/airspace/atc.atc
  Include/XA/kzkc/airspace/class b.artcc
  Include/XA/kzkc/airspace/class c.artcc
  Include/XA/kzkc/airspace/class d.artcc
  Include/XA/kzkc/airspace/kmci_app.artcc
  Include/XA/kzkc/airspace/kzkc_app.artcc
  Include/XA/kzkc/airspace/kzkc_low.artcc
  Include/XA/kzkc/airspace/kzkc_twr.artcc
  Include/XA/kzkc/airspace/staff.atc
  Include/XA/kzkc/airspace/trsa.artcc
  Include/XA/kzkc/geo/kzkc.geo
  Include/XA/kzkc/kaln.tfl
  Include/XA/kzkc/kblv.tfl
  Include/XA/kzkc/kcou.tfl
  Include/XA/kzkc/kcps.tfl
  Include/XA/kzkc/kdec.tfl
  Include/XA/kzkc/kend.tfl
  Include/XA/kzkc/kfoe.tfl
  Include/XA/kzkc/kfri.tfl
  Include/XA/kzkc/kgck.tfl
  Include/XA/kzkc/khut.tfl
  Include/XA/kzkc/kiab.tfl
  Include/XA/kzkc/kict.str
  Include/XA/kzkc/kict.tfl
  Include/XA/kzkc/kidp.tfl
  Include/XA/kzkc/kixd.tfl
  Include/XA/kzkc/kjef.tfl
  Include/XA/kzkc/kjln.tfl
  Include/XA/kzkc/kmci.sid
  Include/XA/kzkc/kmci.str
  Include/XA/kzkc/kmci.tfl
  Include/XA/kzkc/kmdh.tfl
  Include/XA/kzkc/kmhk.tfl
  Include/XA/kzkc/kmkc.tfl
  Include/XA/kzkc/kmwa.tfl
  Include/XA/kzkc/kojc.tfl
  Include/XA/kzkc/krvs.tfl
  Include/XA/kzkc/ksgf.str
  Include/XA/kzkc/ksgf.tfl
  Include/XA/kzkc/ksln.tfl
  Include/XA/kzkc/kspi.str
  Include/XA/kzkc/kspi.tfl
  Include/XA/kzkc/kstj.tfl
  Include/XA/kzkc/kstl.sid
  Include/XA/kzkc/kstl.str
  Include/XA/kzkc/kstl.tfl
  Include/XA/kzkc/ksus.tfl
  Include/XA/kzkc/kswo.tfl
  Include/XA/kzkc/kszl.tfl
  Include/XA/kzkc/ktbn.tfl
  Include/XA/kzkc/ktop.tfl
  Include/XA/kzkc/ktul.sid
  Include/XA/kzkc/ktul.str
  Include/XA/kzkc/ktul.tfl
  Include/XA/kzkc/kwdg.tfl
Labels: USA, graphics, navigation

#44 KMCO Autogen STAR
  Include/XA/kzjx/airac/fixes.fix
  Include/XA/kzjx/airac/vor.vor
  Include/XA/kzjx/kmco.gts
  Include/XA/kzjx/kmco.mva
  Include/XA/kzjx/kmco.sid
  Include/XA/kzjx/kmco.tfl
  Include/XA/kzjx/kmco.txi
  Include/XA/kzma/airac/fixes.fix
  Include/XA/kzma/airac/vor.vor
  Include/XA/kzma/kmco.str
Labels: USA, enhancement, navigation

#46 Updates to KZKC ARTCC isc file and in yaml action
  .github/workflows/ZIP.yaml
  KZKC Kansas City 2102.isc
  KZKC Kansas City ARTCC.isc
Labels: USA, documentation

#43 Updated sid and star for cyow cyqb cyul
  Include/XA/czul/cyow.sid
  Include/XA/czul/cyow.str
  Include/XA/czul/cyqb.sid
  Include/XA/czul/cyqb.str
  Include/XA/czul/cyul.sid
  Include/XA/czul/cyul.str
Labels: Canada, navigation

#53 KSEE & KSMO taxiway labels.
  Include/XA/kzla/ksee.txi
  Include/XA/kzla/ksmo.txi
Labels: USA, enhancement, graphics

#52 KZLA: Rearranged how video maps are stored and defined in isc file
  Include/XA/kzla/airspace/app.artcc
  Include/XA/kzla/app/burbank_laxe.geo
  Include/XA/kzla/app/burbank_laxw.geo
  Include/XA/kzla/app/coast_laxe_snan.geo
  Include/XA/kzla/app/coast_laxe_snas.geo
  Include/XA/kzla/app/coast_laxw_snan.geo
  Include/XA/kzla/app/coast_laxw_snas.geo
  Include/XA/kzla/app/del_rey_laxe.geo
  Include/XA/kzla/app/del_rey_laxw.geo
  Include/XA/kzla/app/del_rey_laxw_snan.geo
  Include/XA/kzla/app/edw_app.geo
  Include/XA/kzla/app/empire_laxe.geo
  Include/XA/kzla/app/empire_laxw.geo
  Include/XA/kzla/app/kbfl_app.geo
  Include/XA/kzla/app/ksba_app.geo
  Include/XA/kzla/app/las_1l-26l.geo
  Include/XA/kzla/app/las_1l.geo
  Include/XA/kzla/app/las_26l.geo
  Include/XA/kzla/app/las_8r.geo
  Include/XA/kzla/app/los_angeles_laxe.geo
  Include/XA/kzla/app/los_angeles_laxw.geo
  Include/XA/kzla/app/lsv_app.geo
  Include/XA/kzla/app/lsv_ctl.geo
  Include/XA/kzla/app/moa.geo
  Include/XA/kzla/app/ntd_app.geo
  Include/XA/kzla/app/pmd_app.geo
  Include/XA/kzla/app/readme.txt
  Include/XA/kzla/app/san_diego_east.geo
  Include/XA/kzla/app/san_diego_west.geo
  Include/XA/kzla/app/videomaps.zip
  Include/XA/kzla/app/yum_app.geo
  KZLA Los Angeles ARTCC.isc
Labels: USA, documentation

#54 KZMA: Updated KTPA airport layout
  Include/XA/kzma/ktpa.tfl
Labels: USA, graphics

#56 KTPA Taxiway fix
  Include/XA/kzma/ktpa.txi
Labels: USA, graphics

#64 Updated ksmo.tfl
  Include/XA/kzla/ksmo.tfl
Labels: USA, graphics

#66 KFMY Taxiway Update
  Include/XA/kzma/kfmy.txi
Labels: USA, graphics

#60 KBOW New taxiway layout
  Include/XA/kzma/kbow.txi
Labels: USA, graphics

#65 KRSW Taxiway update
  Include/XA/kzma/krsw.txi
Labels: USA, graphics

#69 KTMB Updated Taxiways
  Include/XA/kzma/ktmb.txi
Labels: USA, graphics

#70 KHWO Taxiway update
  Include/XA/kzma/khwo.txi
Labels: USA, graphics

#71 Added Combined Sector Archive to Release Assets
  .github/workflows/ZIP.yaml
Labels: documentation

#73 added missing zip of TJZS
  .github/workflows/ZIP.yaml
Labels: documentation

#75 KVNY taxiway labels done.
  Include/XA/kzla/kvny.txi
Labels: USA, graphics

#78 Updated KLAL for Cargo Ramp and added taxi centerlines.
  Include/XA/kzma/klal.str
  Include/XA/kzma/klal.tfl
  Include/XA/kzma/klal.txi
  Include/XA/kzma/klal_txicenterlines.geo
  KZMA Miami ARTCC.isc
Labels: USA, enhancement, graphics

#79 Updated KAPF with new taxiways.
  Include/XA/kzma/kapf.tfl
Labels: USA, enhancement, graphics

#83 CZUL: CYHH airport done.
  Include/XA/czul/cyhh.tfl
Labels: Canada, enhancement, graphics

#62 KSRQ Taxiway update
  Include/XA/kzma/ksrq.gts
  Include/XA/kzma/ksrq.txi
Labels: USA, graphics

#86 Kzma kgpd New taxilayout
  Include/XA/kzma/kpgd.tfl
  Include/XA/kzma/kpgd.txi
Labels: USA, graphics

#89 Added MBPV airport and graphics.
  Include/XA/kzma/mbpv.tfl
  Include/XA/kzma/mbpv.txi
Labels: Bahamas, enhancement, graphics

#92 Removed unused ZAK file
  ZAK Oakland Oceanic.isc
Labels: USA, documentation

#94 Added MYNA FIR
  Include/XA/myna/airac/airports.ap
  Include/XA/myna/airac/awhigh.awh
  Include/XA/myna/airac/awlow.awl
  Include/XA/myna/airac/fixes.fix
  Include/XA/myna/airac/ndb.ndb
  Include/XA/myna/airac/runways.rw
  Include/XA/myna/airac/vor.vor
  Include/XA/myna/airspace/mygf_app.artcc
  Include/XA/myna/airspace/myna.artcc
  Include/XA/myna/airspace/myna_low.artcc
  Include/XA/myna/airspace/mynn_app.artcc
  Include/XA/myna/atc.atc
  Include/XA/myna/geo/coast.geo
  Include/XA/myna/geo/mygf_app.geo
  Include/XA/myna/geo/mynn_app.geo
  Include/XA/myna/myef.sid
  Include/XA/myna/myeh.sid
  Include/XA/myna/myem.sid
  Include/XA/myna/mygf.sid
  Include/XA/myna/mygf.tfl
  Include/XA/myna/mygf.txi
  Include/XA/myna/mynn.gts
  Include/XA/myna/mynn.sid
  Include/XA/myna/mynn.str
  Include/XA/myna/mynn.tfl
  Include/XA/myna/mynn.txi
  MYNA Nassau FIR.isc
Labels: Bahamas, documentation, graphics, navigation

#95 MYNA: Added missing ATC reference in sectorfile
  MYNA Nassau FIR.isc
Labels: Bahamas, documentation

#96 KZMA several Airport labels fixed
  Include/XA/kzma/airspace/Class C.artcc
  Include/XA/kzma/kfpr.txi
  Include/XA/kzma/kpbi.txi
  Include/XA/kzma/kvrb.txi
Labels: USA, graphics

#101 KHHR Taxiways added
  Include/XA/kzla/khhr.txi
Labels: USA, graphics

#103 KZLA: removed dynamic shapes
  Include/XA/kzla/klas.tfl
  Include/XA/kzla/klax.tfl
  Include/XA/kzla/ksan.tfl
Labels: USA, graphics

#105 KZDV: Added runways, airspace labels
  Include/XA/kzdv/airac/runways.rw
  Include/XA/kzdv/airspace/class b.artcc
Labels: USA, graphics, navigation

#107 KZTL: general Updates
  Include/XA/kztl/airac/airports.ap
  Include/XA/kztl/airac/fixes.fix
  Include/XA/kztl/airac/runways.rw
  Include/XA/kztl/airspace/class b.artcc
  Include/XA/kztl/airspace/class c.artcc
  Include/XA/kztl/airspace/class d.artcc
  Include/XA/kztl/airspace/kztl.artcc
  Include/XA/kztl/airspace/kztl_low.artcc
  Include/XA/kztl/airspace/trsa.artcc
  Include/XA/kztl/kbhm.tfl
  KZTL Atlanta ARTCC.isc
Labels: USA, graphics, navigation

#109 Added missing MYNA zip action
  .github/workflows/ZIP.yaml
Labels: Bahamas, bug

#82 KZSE: KBLI airport fully completed.
  Include/XA/kzse/kbli.tfl
  Include/XA/kzse/kbli.txi
Labels: USA, graphics

#124 Updated sector so show CZUL controlled flight levels
  Include/XA/czyz/airspace/control_zones.artcc
  Include/XA/czyz/airspace/czyz.artcc
Labels: Canada, documentation

#125 Updated font sizing to correct how it looks
  Include/XA/czyz/airspace/control_zones.artcc
  Include/XA/czyz/airspace/czyz.artcc
Labels: Canada, beginner friendly, documentation

#126 Kzny updates 190881
  Include/XA/kzny/ad/kjfk_centerlines.geo
  Include/XA/kzny/ad/klga_centerlines.geo
  Include/XA/kzny/airac/fixes.fix
  Include/XA/kzny/airac/vor.vor
  Include/XA/kzny/airspace/class b.artcc
  Include/XA/kzny/airspace/class c.artcc
  Include/XA/kzny/airspace/class d.artcc
  Include/XA/kzny/app/kabe_tracon.geo
  Include/XA/kzny/app/kavp_tracon.geo
  Include/XA/kzny/app/kbgm_tracon.geo
  Include/XA/kzny/app/kelm_tracon.geo
  Include/XA/kzny/app/kmdt_tracon.geo
  Include/XA/kzny/app/kphl_tracon.geo
  Include/XA/kzny/app/krdg_tracon.geo
  Include/XA/kzny/app/kwri_tracon.geo
  Include/XA/kzny/app/n90_ewr.geo
  Include/XA/kzny/app/n90_isp.geo
  Include/XA/kzny/app/n90_jfk_13s.geo
  Include/XA/kzny/app/n90_jfk_22s.geo
  Include/XA/kzny/app/n90_jfk_31s.geo
  Include/XA/kzny/app/n90_jfk_4s.geo
  Include/XA/kzny/app/n90_lga.geo
  Include/XA/kzny/app/n90_lib_catskill.geo
  Include/XA/kzny/app/n90_lib_dep.geo
  Include/XA/kzny/app/n90_outline.geo
  Include/XA/kzny/app/readme.txt
  Include/XA/kzny/app/videomaps.zip
  Include/XA/kzny/kewr.gts
  Include/XA/kzny/kewr.sid
  Include/XA/kzny/kewr.tfl
  Include/XA/kzny/kewr.txi
  Include/XA/kzny/kfrg.sid
  Include/XA/kzny/kfrg.txi
  Include/XA/kzny/kisp.sid
  Include/XA/kzny/kisp.txi
  Include/XA/kzny/kjfk.gts
  Include/XA/kzny/kjfk.sid
  Include/XA/kzny/kjfk.tfl
  Include/XA/kzny/kjfk.txi
  Include/XA/kzny/kldj.str
  Include/XA/kzny/klga.gts
  Include/XA/kzny/klga.sid
  Include/XA/kzny/klga.tfl
  Include/XA/kzny/klga.txi
  Include/XA/kzny/kteb.sid
  Include/XA/kzny/kteb.txi
  KZNY New York ARTCC.isc
Labels: USA, graphics

#131 KZWY: Oceanic updates
  .github/workflows/ZIP.yaml
  CZQX Gander Oceanic FIR.isc
  KZWY New York Oceani FIR.isc
Labels: USA, graphics, navigation

#132 KZWY: fixed bug in actions for kzwy
  .github/workflows/ZIP.yaml
Labels: bug

#134 KFRG Added ramp and taxiway H
  Include/XA/kzny/kfrg.tfl
  Include/XA/kzny/kfrg.txi
Labels: USA, enhancement, graphics, navigation

#133 Created CYTR Taxiway labels
  Include/XA/czyz/cytr.txi
Labels: Canada, beginner friendly, graphics, navigation

#136 Bermuda, ATC updates
  KZWY New York Oceani FIR.isc
Labels: USA, Updates
