Repository ivao-xa/sectorfiles, pull requests merged in 2021-08, with the labels that each got.

#187 Kzhu updates 190881
  .github/workflows/ZIP.yaml
  Include/XA/kzhu/ARTCC/atc.atc
  Include/XA/kzhu/ARTCC/class b.artcc
  Include/XA/kzhu/ARTCC/kzhu.artcc
  Include/XA/kzhu/kmsy.mva
  Include/XA/kzhu/kzhu_aor.tfl
  Include/XA/kzhu/kzhu_ctr.tfl
  Include/XA/kzhu/kzhu_occ_aor.tfl
Labels: graphics

#192 CYTZ Layout Updated 2021
  CZYZ Toronto FIR.isc
  Include/XA/czyz/cytz.tfl
  Include/XA/czyz/cytz.txi
  Include/XA/czyz/cytz_pier.geo
  Include/XA/czyz/cytz_stoplines.geo
  Include/XA/czyz/cytz_txicenterlines.geo
Labels: enhancement, beginner friendly, Canada, graphics, Updates

#193 New layout for London CYXU
  CZYZ Toronto FIR.isc
  Include/XA/czyz/cyxu.tfl
  Include/XA/czyz/cyxu.txi
  Include/XA/czyz/cyxu_pier.geo
  Include/XA/czyz/cyxu_stoplines.geo
  Include/XA/czyz/cyxu_txicenterlines.geo
Labels: enhancement, beginner friendly, Canada, graphics, Updates

#195 KZLA: VFR Reporting Points and TFLs
  Include/XA/kzla/kavx.tfl
  Include/XA/kzla/kbfl.tfl
  Include/XA/kzla/kbur.tfl
  Include/XA/kzla/kbur.vfi
  Include/XA/kzla/kcma.tfl
  Include/XA/kzla/kcno.tfl
  Include/XA/kzla/kcrq.tfl
  Include/XA/kzla/kful.tfl
  Include/XA/kzla/khhr.tfl
  Include/XA/kzla/khnd.tfl
  Include/XA/kzla/kins.tfl
  Include/XA/kzla/klas.tfl
  Include/XA/kzla/klax.mva
  Include/XA/kzla/klax.tfl
  Include/XA/kzla/klax.vfi
  Include/XA/kzla/klgb.tfl
  Include/XA/kzla/klgb.vfi
  Include/XA/kzla/klgf.tfl
  Include/XA/kzla/kmhv.tfl
  Include/XA/kzla/kmyf.tfl
  Include/XA/kzla/knfg.tfl
  Include/XA/kzla/knid.tfl
  Include/XA/kzla/knjk.tfl
  Include/XA/kzla/knkx.tfl
  Include/XA/kzla/knrs.tfl
  Include/XA/kzla/knsi.tfl
  Include/XA/kzla/kntd.tfl
  Include/XA/kzla/knuc.tfl
  Include/XA/kzla/knxp.tfl
  Include/XA/kzla/knyl.tfl
  Include/XA/kzla/knzy.tfl
  Include/XA/kzla/kont.tfl
  Include/XA/kzla/koxr.tfl
  Include/XA/kzla/kpmd.tfl
  Include/XA/kzla/kpsp.tfl
  Include/XA/kzla/kral.tfl
  Include/XA/kzla/kriv.tfl
  Include/XA/kzla/krnm.tfl
  Include/XA/kzla/ksan.tfl
  Include/XA/kzla/ksan.vfi
  Include/XA/kzla/ksba.tfl
  Include/XA/kzla/ksbd.tfl
  Include/XA/kzla/ksbp.tfl
  Include/XA/kzla/ksdm.tfl
  Include/XA/kzla/ksee.tfl
  Include/XA/kzla/ksli.tfl
  Include/XA/kzla/ksmo.tfl
  Include/XA/kzla/ksmx.tfl
  Include/XA/kzla/ksna.tfl
  Include/XA/kzla/ksna.vfi
  Include/XA/kzla/ktoa.tfl
  Include/XA/kzla/kvbg.tfl
  Include/XA/kzla/kvcv.tfl
  Include/XA/kzla/kvgt.tfl
  Include/XA/kzla/kvny.tfl
  Include/XA/kzla/kwhp.tfl
  Include/XA/kzla/kwjf.tfl
  Include/XA/kzla/l22.tfl
  Include/XA/kzla/l35.tfl
  KZLA Los Angeles ARTCC.isc
Labels: USA, navigation, graphics, Updates
