Repository ivao-xa/sectorfiles, pull requests merged in 2021-07, with the labels that each got.

#143 KZDV - KCFO airport layout added and voice ATIS for ARTCC
  Include/XA/kzdv/default.atis
  Include/XA/kzdv/kcfo.tfl
  Include/XA/kzdv/kcfo.txi
  KZDV Denver ARTCC.isc
Labels: USA, documentation, graphics, navigation

#148 Updated KZSE procedures for #144.
  Include/XA/kzse/kgeg.sid
  Include/XA/kzse/kgeg.str
  Include/XA/kzse/knuw.sid
  Include/XA/kzse/knuw.str
  Include/XA/kzse/kpdx.sid
  Include/XA/kzse/kpdx.str
  Include/XA/kzse/ksea.sid
  Include/XA/kzse/ksea.str
  Include/XA/kzse/kska.str
Labels: USA, Updates, navigation

#151 Updated missing ramps at KLAX
  Include/XA/kzla/klax.tfl
Labels: USA, Updates, enhancement, graphics

#153 Redone CYYZ from scratch
  CZYZ Toronto FIR.isc
  Include/XA/czyz/cyyz.tfl
  Include/XA/czyz/cyyz.txi
  Include/XA/czyz/cyyz_stoplines.geo
  Include/XA/czyz/cyyz_txicenterlines.geo
Labels: Canada, Updates, enhancement, graphics

#155 Updated fixes and VOR's for ZYZ Sectorfile.
  Include/XA/czyz/airac/fixes.fix
  Include/XA/czyz/airac/vor.vor
Labels: Canada, Updates, navigation

#159 Montreal Layout updated
  CZUL Montreal FIR.isc
  Include/XA/czul/ad/cyul.fcl
  Include/XA/czul/cyul.tfl
  Include/XA/czul/cyul.txi
  Include/XA/czul/cyul_stoplines.geo
  Include/XA/czul/cyul_txicenterlines.geo
Labels: Canada, Updates, documentation, graphics

#162 Updated all Canadian FIR's for voice ATIS function
  CDQX Gander FIR.isc
  CZEG Edmonton FIR.isc
  CZQM Moncton FIR.isc
  CZUL Montreal FIR.isc
  CZVR Vancouver FIR.isc
  CZWG Winnipeg FIR.isc
  CZYZ Toronto FIR.isc
  Include/XA/czeg/default.atis
  Include/XA/czqm/default.atis
  Include/XA/czqx/default.atis
  Include/XA/czul/default.atis
  Include/XA/czvr/default.atis
  Include/XA/czwg/default.atis
  Include/XA/czyz/default.atis
Labels: Canada, Updates, enhancement

#164 Added Voice ATIS for all ARTCC
  Include/XA/kzab/default.atis
  Include/XA/kzak/default.atis
  Include/XA/kzau/default.atis
  Include/XA/kzbw/default.atis
  Include/XA/kzdc/default.atis
  Include/XA/kzfw/default.atis
  Include/XA/kzhu/default.atis
  Include/XA/kzid/default.atis
  Include/XA/kzjx/default.atis
  Include/XA/kzkc/default.atis
  Include/XA/kzlc/default.atis
  Include/XA/kzma/default.atis
  Include/XA/kzme/default.atis
  Include/XA/kzmp/default.atis
  Include/XA/kzny/default.atis
  Include/XA/kzoa/default.atis
  Include/XA/kzob/default.atis
  Include/XA/kzse/default.atis
  Include/XA/kztl/default.atis
  Include/XA/myna/default.atis
  Include/XA/paza/default.atis
  Include/XA/pgzu/default.atis
  Include/XA/phzh/default.atis
  Include/XA/tjzs/default.atis
  KZAB Albuquerque 2014.isc
  KZAK _W_CTR 2103.isc
  KZAK_CW_CTR 2103.isc
  KZAK_E_CTR 2103.isc
  KZAK_NW_CTR 2103.isc
  KZAK_N_CTR 2103.isc
  KZAK_S_CTR 2103.isc
  KZAU Chicago 2101.isc
  KZBW Boston ARTCC.isc
  KZDC Washington ARTCC.isc
  KZFW Fort Worth ARTCC.isc
  KZHU Houston ARTCC 2012.isc
  KZID Indianapolis 2014.isc
  KZJX Jacksonville ARTCC.isc
  KZKC Kansas City ARTCC.isc
  KZLC Salt Lake 2103.isc
  KZMA Miami ARTCC.isc
  KZME Memphis 2013-1.isc
  KZMP Minneapolis ARTCC.isc
  KZNY New York ARTCC.isc
  KZOA Oakland ARTCC.isc
  KZOB Cleveland ARTCC.isc
  KZSE Seattle ARTCC.isc
  KZTL Atlanta ARTCC.isc
  MYNA Nassau FIR.isc
  PAZA Anchorage ARTCC.isc
  PGZU Guam CENRAP.isc
  PHZH Honolulu ARTCC.isc
  TJZS San Juan ARTCC.isc
Labels: Bahamas, USA, Updates, enhancement

#165 Updated Taxiway Labels for Montreal
  Include/XA/czul/cyul.txi
Labels: Canada, Updates, beginner friendly, navigation

#171 general updates
  Include/XA/kzma/kmco.vfi
  Include/XA/kzma/kmia.vfi
  Include/XA/kzma/kmia.vrt
  Include/XA/kzma/kpbi.vfi
  Include/XA/kzma/krsw.vfi
  Include/XA/kzma/ktpa.vfi
Labels: Updates

#174 Fix Filler for all Canadian Sectors
  Include/XA/czeg/airac/fixes.fix
  Include/XA/czeg/airac/vor.vor
  Include/XA/czqx/airac/fixes.fix
  Include/XA/czqx/airac/vor.vor
  Include/XA/czul/airac/czul.fix
  Include/XA/czul/airac/czul.vor
  Include/XA/czvr/airac/fixes.fix
  Include/XA/czvr/airac/vor.vor
  Include/XA/czwg/airac/fixes.fix
  Include/XA/czwg/airac/vor.vor
  Include/XA/czyz/airac/fixes.fix
  Include/XA/czyz/airac/vor.vor
Labels: Canada, Updates, navigation

#179 KZLA: New KLGB layout, adjusted taxiways at KSBD updated gates at KONT
  Include/XA/kzla/airac/runways.rw
  Include/XA/kzla/klgb.gts
  Include/XA/kzla/klgb.tfl
  Include/XA/kzla/klgb.txi
  Include/XA/kzla/kont.gts
  Include/XA/kzla/kont.txi
  Include/XA/kzla/ksbd.txi
Labels: USA, Updates, graphics

#182 Added shared area for ZYZ and ZOB
  Include/XA/czyz/airac/airports.ap
  Include/XA/czyz/airac/runways.rw
  Include/XA/czyz/airspace/czyz.artcc
Labels: Canada, Updates, enhancement, graphics, navigation

#183 updates
  Include/XA/kzab/GEO/kzab.geo
  Include/XA/kzab/kabq_ap.ftl
  Include/XA/kzab/kabq_app.tfl
  Include/XA/kzab/kabq_twr.ftl
  Include/XA/kzab/kabq_twr.tfl
  Include/XA/kzab/kama_app.ftl
  Include/XA/kzab/kama_app.tfl
  Include/XA/kzab/kama_twr.tfl
  Include/XA/kzab/kdma_twr.ftl
  Include/XA/kzab/kdma_twr.tfl
  Include/XA/kzab/khmn_app.tfl
  Include/XA/kzab/kphx_app.tfl
  Include/XA/kzab/kphx_twr.tfl
  Include/XA/kzab/ktus_app.tfl
  Include/XA/kzab/kzab_ctr.tfl
Labels: USA

#184 Czqm updates 190881
  Include/XA/czqm/airac/fixes.fix
  Include/XA/czqm/airac/vor.vor
  Include/XA/czqm/cybc.sid
  Include/XA/czqm/cybc.str
  Include/XA/czqm/cych.str
  Include/XA/czqm/cycl.str
  Include/XA/czqm/cyes.sid
  Include/XA/czqm/cyes.str
  Include/XA/czqm/cyfc.sid
  Include/XA/czqm/cyfc.str
  Include/XA/czqm/cygp.str
  Include/XA/czqm/cygr.str
  Include/XA/czqm/cygv.str
  Include/XA/czqm/cyhr.str
  Include/XA/czqm/cyhz.sid
  Include/XA/czqm/cyhz.str
  Include/XA/czqm/cyid.str
  Include/XA/czqm/cyjt.str
  Include/XA/czqm/cyme.str
  Include/XA/czqm/cyna.str
  Include/XA/czqm/cypd.str
  Include/XA/czqm/cypn.str
  Include/XA/czqm/cyqi.str
  Include/XA/czqm/cyqm.sid
  Include/XA/czqm/cyqm.str
  Include/XA/czqm/cyqy.sid
  Include/XA/czqm/cyqy.str
  Include/XA/czqm/cysj.sid
  Include/XA/czqm/cysj.str
  Include/XA/czqm/cysu.str
  Include/XA/czqm/cysz.str
  Include/XA/czqm/cytn.str
  Include/XA/czqm/cyvb.str
  Include/XA/czqm/cyxk.str
  Include/XA/czqm/cyyg.sid
  Include/XA/czqm/cyyg.str
  Include/XA/czqm/cyyy.sid
  Include/XA/czqm/cyyy.str
  Include/XA/czqm/cyzv.sid
  Include/XA/czqm/cyzv.str
  Include/XA/czqm/cyzx.str
  Include/XA/czqm/czbf.str
  Include/XA/kzob/airspace/kzob approaches.artcc
  OCC_2107.isc
Labels: Canada
