Repository ivao-xa/sectorfiles, pull requests merged in 2021-12, with the labels that each got.

#233 zyz-split sectors added
  CZYZ Toronto FIR.isc
  Include/XA/czyz/airspace/app.artcc
  Include/XA/czyz/app/cyyz_msa.geo
  Include/XA/czyz/atc.atc
Labels: enhancement, Canada, graphics, Updates

#234 updated labels and atc
  Include/XA/kzma/airspace/kzma_high.artcc
  Include/XA/kzma/atc.atc
Labels: USA, graphics, Updates

#236 ZDC layout reductions
  Include/XA/kzdc/kacy.tfl
  Include/XA/kzdc/kcho.tfl
  Include/XA/kzdc/kdov.tfl
  Include/XA/kzdc/kfay.tfl
  Include/XA/kzdc/kgsb.tfl
  Include/XA/kzdc/kilm.tfl
  Include/XA/kzdc/knhk.tfl
  Include/XA/kzdc/knkt.tfl
  Include/XA/kzdc/kpct.tfl
  Include/XA/kzdc/kphl.tfl
  Include/XA/kzdc/kpob.txi
  Include/XA/kzdc/krdu.tfl
  Include/XA/kzdc/krdu.txi
  Include/XA/kzdc/kroa.tfl
Labels: USA, Updates

#237 Kzse updates 190881
  Include/XA/kzse/airspace/kzse.artcc
  Include/XA/kzse/atc.atc
  Include/XA/kzse/kalw.txi
  Include/XA/kzse/kbfi.txi
  Include/XA/kzse/keug.txi
  Include/XA/kzse/kgeg.txi
  Include/XA/kzse/kgrf.txi
  Include/XA/kzse/khio.txi
  Include/XA/kzse/klmt.txi
  Include/XA/kzse/klws.txi
  Include/XA/kzse/kmfr.txi
  Include/XA/kzse/kmwh.txi
  Include/XA/kzse/knuw.txi
  Include/XA/kzse/kolm.txi
  Include/XA/kzse/koth.txi
  Include/XA/kzse/kpae.txi
  Include/XA/kzse/kpdt.txi
  Include/XA/kzse/kpdx.txi
  Include/XA/kzse/kpsc.txi
  Include/XA/kzse/krdm.txi
  Include/XA/kzse/krnt.txi
  Include/XA/kzse/ksea.txi
  Include/XA/kzse/ksff.txi
  Include/XA/kzse/kska.txi
  Include/XA/kzse/ksle.txi
  Include/XA/kzse/ktcm.txi
  Include/XA/kzse/ktiw.txi
  Include/XA/kzse/kttd.txi
  Include/XA/kzse/kykm.txi
Labels: enhancement, USA, graphics, Updates

#241 Kzbw updates 190881
  Include/XA/kzbw/airac/airports.ap
  Include/XA/kzbw/airac/fixes.fix
  Include/XA/kzbw/airac/runways.rw
  Include/XA/kzbw/airac/vor.vor
  Include/XA/kzbw/airspace/kzbw_high.artcc
  Include/XA/kzbw/airspace/zbw class b.artcc
  Include/XA/kzbw/airspace/zbw class c.artcc
  Include/XA/kzbw/airspace/zbw class d.artcc
  Include/XA/kzbw/atc.atc
  Include/XA/kzbw/kewr.str
  Include/XA/kzbw/kjfk.str
  Include/XA/kzbw/klga.str
  Include/XA/kzny/txkf.tfl
  Include/XA/kzny/txkf.txi
  KZBW Boston ARTCC.isc
Labels: USA, navigation, Updates

#243 190881 kzjx updates
  Include/XA/kzjx/atc.atc
  Include/XA/kzjx/kmco.tfl
  Include/XA/kzjx/kmco.txi
  Include/XA/kzjx/ktpa.gts
  Include/XA/kzjx/ktpa.tfl
  Include/XA/kzjx/ktpa.txi
  Include/XA/kzjx/ktpa.vfi
  Include/XA/kzma/kmco.tfl
  Include/XA/kzma/kmco.txi
Labels: USA, graphics, Updates

#244 added CDQX to handoff list
  Include/XA/kzbw/atc.atc
Labels: USA
