Repository ivao-xa/sectorfiles, pull requests merged in 2022-05, with the labels that each got.

#275 updated zmp atc list
  Include/XA/kzmp/atc.atc
Labels: bug, USA, Updates

#276 [KZDV] Removed KDEN copy file with weird folder name.
  include/XA/kzdv/kden - Copy.tfl
Labels: bug, documentation, USA

#277 [KZLA] Sector Color Naming Clash
  Include/XA/kzla/kavx.tfl
  Include/XA/kzla/kbfl.tfl
  Include/XA/kzla/kbur.tfl
  Include/XA/kzla/kcno.tfl
  Include/XA/kzla/kcrq.tfl
  Include/XA/kzla/khhr.tfl
  Include/XA/kzla/khnd.tfl
  Include/XA/kzla/klas.tfl
  Include/XA/kzla/klax.tfl
  Include/XA/kzla/klgb.tfl
  Include/XA/kzla/kmyf.tfl
  Include/XA/kzla/knkx.tfl
  Include/XA/kzla/knuc.tfl
  Include/XA/kzla/knyl.tfl
  Include/XA/kzla/knzy.tfl
  Include/XA/kzla/kont.tfl
  Include/XA/kzla/kpmd.tfl
  Include/XA/kzla/kpsp.tfl
  Include/XA/kzla/kriv.tfl
  Include/XA/kzla/ksan.tfl
  Include/XA/kzla/ksba.tfl
  Include/XA/kzla/ksbd.tfl
  Include/XA/kzla/ksbp.tfl
  Include/XA/kzla/ksmo.tfl
  Include/XA/kzla/ksna.tfl
  Include/XA/kzla/ktoa.tfl
  Include/XA/kzla/kvgt.tfl
  Include/XA/kzla/kvny.tfl
  KZLA Los Angeles ARTCC.isc
Labels: bug, USA, graphics

#281 ZWY Sectorfile Naming
  KZWY New York Oceanic FIR.isc
Labels: bug, USA

#282 [ZLA] Fixed typo in TRSA points
  Include/XA/kzla/airspace/trsa.artcc
Labels: bug, beginner friendly, USA, graphics
