Repository ivao-xa/sectorfiles, pull requests merged in 2022-02, with the labels that each got.

#258 KZWY update frequencies
  KZWY New York Oceani FIR.isc
Labels: USA, Updates

#257 190881 multiple FIR updates
  CZQX Gander Oceanic FIR.isc
  CZYZ Toronto FIR.isc
  Include/XA/czyz/airac/airports.ap
  Include/XA/czyz/airac/awh.awh
  Include/XA/czyz/airac/awl.awl
  Include/XA/czyz/airac/runways.rw
  Include/XA/czyz/airspace/control_zones.artcc
  Include/XA/czyz/airspace/czyz.artcc
  Include/XA/czyz/airspace/czyz_aor.tfl
  Include/XA/czyz/airspace/kzob approaches.artcc
  Include/XA/czyz/airspace/terminal_control_areas.artcc
  Include/XA/czyz/kbuf.str
  Include/XA/czyz/kdtw.str
Labels: Canada, graphics, Updates

#262 [KZHU] correct runway labels for austin
  Include/XA/kzhu/airac/runways.rw
Labels: bug, USA, navigation
