Repository ivao-xa/sectorfiles, pull requests merged in 2022-04, with the labels that each got.

#269 updated readme
  README.md
Labels: documentation

#270 190881 generalupdates
  Include/XA/kzdc/airac/airports.ap
  Include/XA/kzdc/airac/runways.rw
  Include/XA/kzdv/kden.tfl
  Include/XA/kzdv/kden.txi
  Include/XA/kzma/app/mia.artcc
  Include/XA/kzma/app/pbi.artcc
  Include/XA/kzma/kmia.txi
  include/XA/kzdv/kden - Copy.tfl
Labels: USA, graphics

#273 [KZLA] Fixed coordinate casing at KVNY
  Include/XA/kzla/klgb.gts
  Include/XA/kzla/klgb.txi
  Include/XA/kzla/kont.gts
  Include/XA/kzla/ksbd.txi
  Include/XA/kzla/kvny.txi
Labels: bug, USA, navigation

#274 ord updates
  Include/XA/kzau/kord.tfl
  Include/XA/kzau/kord.txi
  Include/XA/kzkc/ad/kmci.geo
  Include/XA/kzkc/airac/airports.ap
  Include/XA/kzkc/airac/runways.rw
  Include/XA/kzkc/atc.atc
  Include/XA/kzkc/kmci.gts
  Include/XA/kzkc/kmci.txi
Labels: USA, graphics
