Repository ivao-xa/sectorfiles, pull requests merged in 2022-01, with the labels that each got.

#245 Kzab updates 190881
  Include/XA/kzab/airspace/class b.artcc
  Include/XA/kzab/airspace/class c.artcc
  Include/XA/kzab/airspace/class d.artcc
  Include/XA/kzab/atc.atc
Labels: enhancement, USA, graphics

#249 SoCal TEC Routes
  Include/XA/kzla/atc.atc
Labels: enhancement, USA, navigation, Backlog

#246 [KZLA] Updated L30 position names and removed missing DEP positions
  Include/XA/kzla/atc.atc
Labels: USA, graphics, Updates

#248 KLAS Taxiway Colors
  Include/XA/kzla/klas.tfl
Labels: bug, USA, graphics

#252 fixed typo for TJZS
  .github/workflows/ZIP.yaml
Labels: bug

#253 Update atc file
  Include/XA/kzny/atc.atc
Labels: USA, Updates

#254 zau updates
  Include/XA/kzau/airspace/class b.artcc
  Include/XA/kzau/airspace/class c.artcc
  Include/XA/kzau/airspace/class d.artcc
  Include/XA/kzau/airspace/trsa.artcc
  Include/XA/kzau/app/kmke_25l_app.geo
  Include/XA/kzau/atc.atc
  KZAU Chicago ARTCC.isc
Labels: enhancement, USA, navigation

#255 updated airspaces, atc and fixes
  Include/XA/kzfw/airspace/class b.artcc
  Include/XA/kzfw/airspace/class c.artcc
  Include/XA/kzfw/airspace/class d.artcc
  Include/XA/kzfw/atc.atc
Labels: USA, Updates

#256 190881 kzob updates
  Include/XA/kzob/airac/airports.ap
  Include/XA/kzob/airac/runways.rw
  Include/XA/kzob/airspace/zob class b.artcc
  Include/XA/kzob/airspace/zob class c.artcc
  Include/XA/kzob/airspace/zob class d.artcc
  Include/XA/kzob/atc.atc
  Include/XA/kzob/cyyz.str
Labels: Canada, Updates
